// Team name to emoji flag mapping for FIFA World Cup 2026
export const TEAM_FLAGS: Record<string, string> = {
  Mexico: "🇲🇽",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  Czechia: "🇨🇿",
  Canada: "🇨🇦",
  "Bosnia-Herzegovina": "🇧🇦",
  Qatar: "🇶🇦",
  Switzerland: "🇨🇭",
  "United States": "🇺🇸",
  Paraguay: "🇵🇾",
  Australia: "🇦🇺",
  Türkiye: "🇹🇷",
  Germany: "🇩🇪",
  Curaçao: "🇨🇼",
  Netherlands: "🇳🇱",
  Japan: "🇯🇵",
  "Ivory Coast": "🇨🇮",
  Ecuador: "🇪🇨",
  Sweden: "🇸🇪",
  Tunisia: "🇹🇳",
  Spain: "🇪🇸",
  "Cape Verde": "🇨🇻",
  Morocco: "🇲🇦",
  Haiti: "🇭🇹",
  Brazil: "🇧🇷",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "New Zealand": "🇳🇿",
  Egypt: "🇪🇬",
  Belgium: "🇧🇪",
  Iran: "🇮🇷",
  Uruguay: "🇺🇾",
  "Saudi Arabia": "🇸🇦",
  France: "🇫🇷",
  Senegal: "🇸🇳",
  Iraq: "🇮🇶",
  Norway: "🇳🇴",
  Argentina: "🇦🇷",
  Algeria: "🇩🇿",
  Jordan: "🇯🇴",
  Austria: "🇦🇹",
  Portugal: "🇵🇹",
  "Congo DR": "🇨🇩",
  Uzbekistan: "🇺🇿",
  Colombia: "🇨🇴",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Croatia: "🇭🇷",
  Ghana: "🇬🇭",
  Panama: "🇵🇦",
};

export function getTeamFlag(teamName: string): string {
  return TEAM_FLAGS[teamName] ?? "⚽";
}
